<script>
$(document).ready(function(){
  $("#button1").click(function(){
    $("#options").load("./dynamic/mysinger.php");
  });
   $("#create_list").click(function(){
    $("#options").load("./dynamic/create_new_list.php");
  });
});
</script>