<script>
$(document).ready(function(){
  $("#button1").click(function(){
    $("#options").load("./dynamic/mysinger.php");
  });
   $("#button2").click(function(){
    $("#options").load("./dynamic/mysongs.php");
  });
});
</script>